name: CI

on:
  push:
    branches: [main]
    paths-ignore:
      - '*.md'

jobs:
  test:
    name: ✅ CI
    runs-on: ubuntu-latest
    if: contains(github.event.head_commit.message, '✔️') == false && contains(github.event.head_commit.message, '[ci skip]') == false

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: 16

      - name: Install dependencies
        run: npm install

      - name: Run unit & integration tests
        run: npm test
